### PR TITLE
auto start rush service when deployed standalone, fix issue #762

### PR DESCRIPTION
**Pull request by peterpd**
this only includes changes for rush service, though other services have the same issue and need be addressed as well.
we would like to get feed back on if we are on the right trace to address the issue.

### CODE REVIEW

**Comment by ajordens** [comment]
Any feedback @ewiseblatt?

**Comment by duftler** [comment]
Or @dpeterka ?

**Comment by ewiseblatt** [comment]
@seank, can you have a look?

**Comment by ewiseblatt** [comment]
@skorten could you have a look?

**Comment by ewiseblatt** [comment]
disregard that, wrong id

**Comment by peterpd** [comment]
We’re facing the issue of auto start services when they are deployed on separate VMs. 
Feedback will help us and other users move forward.
The change intends not to change the way it works with all services are deployed in a single VM. 
If there is another way of achieving the same goal, I’m open to suggestions.

**Comment by ewiseblatt** [comment]
@dpeterka, @skorten 
Understood. I'm not familiar with the intent of how the upstart mechanism was supposed to handle this.
We used to have a different startup mechanism which accomodated non-homogenous deployments, but it got replaced with upstart. What you are doing looks ok to me, but David or Sean are more familiar with any implications so I was soliciting their input.

**Comment by dpeterka** [comment]
upstart scripts are enabled by default so I'm not sure why the extra check is required for the service here, the depends check seems redundant.

**Comment by peterpd** [comment]
@dpeterka, @ewiseblatt
Initially we tried without dependency check. but in case all services installed on a single VM, their startup order is not guaranteed as specified in spinnaker.conf file.

specifically, when all installed together, spinnaker service starts the services in a certain order (spinnaker.conf). in this case, the services should not auto start on their own.

**Comment by peterpd** [comment]
@dpeterka, @ewiseblatt
Thanks for the comments.
Let me try to explain the changes in detail, as I did not explain well.
The approach is kind of convoluted. would be better if could find a simpler solution.
the purpose is to auto start rush when spinnaker is not present, and when spinnaker is present let spinnaker start rush .
1.	Added a new service rush-trigger, its purpose is to trigger rush service, if spinnaker is not present (installed separately).
rush-trigger.conf:
start on filesystem or runlevel [2345]	
	script
	  # temporarily allow command to fail without exiting the script, when spinnaker is not present
	  set +e
          # check if spinnaker is present
	  status spinnaker
	  # capture status of spinnaker, 0 if spinnaker is present, non-zero otherwise
	  SPINNAKER_EXISTS_CHECK="$(echo $?)"
	  # restore to the way it was
	  set -e
	  if [ $SPINNAKER_EXISTS_CHECK != 0 ]
	  then
            # spinnaker is not present, create event “rush_triggered” to trigger rush service
	    initctl emit rush_triggered
	    exit 0
	  fi
	end script

2.	Added “start on rush_triggered” to rush.conf
Event “rush_triggered” is only generated if spinnaker is missing ((installed separately).
If all installed together, “start on rush_triggered” has no effect.

**Comment by dpeterka** [comment]
I haven't had time to play but I think adding the following might work a little more consistantly.  I think the better fix would be to ensure a service can install by itself and spinnaker rpm to add on the master start script so it doesn't impact standalone stuff.

```
pre-start script
  [ ! -f /etc/init/spinnaker.com ] && env STANDALONE=true;
end 

start on STANDALONE="true";```

**Comment by peterpd** [comment]
@dpeterka : thanks for the comment. checking file spinnaker.conf is a good simple way vs doing status spinnaker. but upstart does not support start on env variables, right?

**Comment by dpeterka** [comment]
It should I referenced their documentation.

**Comment by peterpd** [comment]
@dpeterka : thanks for the comment.
start on only supports env variables contained within an EVENT.
section 6.33 in upstart cookbook:
http://upstart.ubuntu.com/cookbook

**Pull request closed without merging**
